-- MySQL Script generated by MySQL Workbench
-- mar 16 nov 2021, 14:10:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema belexo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `belexo` ;

-- -----------------------------------------------------
-- Schema belexo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `belexo` ;

USE `belexo` ;

-- -----------------------------------------------------
-- Table `belexo`.`fsnodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`fsnodes` ;

CREATE TABLE IF NOT EXISTS `belexo`.`fsnodes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `type` VARCHAR(1) NOT NULL, -- 'F' for file, 'D' for directory
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `father` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `father_idx` (`father` ASC) VISIBLE,
  CONSTRAINT `father_fk`
    FOREIGN KEY (`father`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


-- -----------------------------------------------------
-- Table `belexo`.`str_fs_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`str_fs_props` ;

CREATE TABLE IF NOT EXISTS `belexo`.`str_fs_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `value` TEXT NULL,
  `node` INT NULL,
  `meta` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `sn_node_idx` (`node` ASC) VISIBLE,
  INDEX `sn_name_idx` (`name` ASC) VISIBLE,
  INDEX `sn_value_idx` (`value`(256) ASC) VISIBLE,
  INDEX `sn_name_node_idx` (`name` ASC, `node` ASC) VISIBLE,
  INDEX `sn_value_node_idx` (`value`(256) ASC, `node` ASC) VISIBLE,
  CONSTRAINT `str_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


-- -----------------------------------------------------
-- Table `belexo`.`int_fs_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`int_fs_props` ;

CREATE TABLE IF NOT EXISTS `belexo`.`int_fs_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `value` INT NULL,
  `node` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `in_node_idx` (`node` ASC) VISIBLE,
  INDEX `in_name_idx` (`name` ASC) VISIBLE,
  INDEX `in_value_idx` (`value` ASC) VISIBLE,
  INDEX `in_name_node_idx` (`name` ASC, `node` ASC) VISIBLE,
  INDEX `in_value_node_idx` (`value` ASC, `node` ASC) VISIBLE,
  CONSTRAINT `in_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


-- -----------------------------------------------------
-- Table `belexo`.`blob_fs_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`blob_fs_props` ;

CREATE TABLE IF NOT EXISTS `belexo`.`blob_fs_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `value` BLOB NULL,
  `node` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `bn_node_idx` (`node` ASC) VISIBLE,
  INDEX `bn_name_idx` (`name` ASC) VISIBLE,
  INDEX `bn_name_node_idx` (`name` ASC, `node` ASC) VISIBLE,
  CONSTRAINT `bn_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


-- -----------------------------------------------------
-- Table `belexo`.`unstructured`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`unstructured` ;

CREATE TABLE IF NOT EXISTS `belexo`.`unstructured` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` MEDIUMTEXT NULL,
  `node` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `u_node_idx` (`node` ASC) VISIBLE,
  CONSTRAINT `u_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;

-- -----------------------------------------------------
-- Table `belexo`.`tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`tokens` ;

CREATE TABLE IF NOT EXISTS `belexo`.`tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(1024) NULL,
  `position` INT NOT NULL,
  `begin` INT NOT NULL,
  `end` INT NOT NULL,
  `node` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tok_text_idx` (`text`(256) ASC) VISIBLE,
  INDEX `tok_node_idx` (`node` ASC) VISIBLE,
  INDEX `tok_text_node_idx` (`text`(256) ASC, `node` ASC) VISIBLE,
  CONSTRAINT `tok_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;

-- -----------------------------------------------------
-- Table `belexo`.`annotations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belexo`.`annotations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `layer` VARCHAR(1024) NOT NULL,
  `value` VARCHAR(1024) NULL,
  `begin` INT NOT NULL,
  `end` INT NOT NULL,
  `node` INT NOT NULL,
  `sameas` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ann_value_idx` (`value`(256) ASC) VISIBLE,
  INDEX `ann_node_idx` (`node` ASC) VISIBLE,
  INDEX `ann_layer_node_idx` (`layer`(256) ASC, `node` ASC) VISIBLE,
  INDEX `ann_value_node_idx` (`value`(256) ASC, `node` ASC) VISIBLE,
  INDEX `ann_value_layer_node_idx` (`value`(256) ASC, `layer`(256) ASC, `node` ASC) VISIBLE,
  CONSTRAINT `ann_node_fk`
    FOREIGN KEY (`node`)
    REFERENCES `belexo`.`fsnodes` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `ann_ann_fk`
    FOREIGN KEY (`sameas`)
    REFERENCES `belexo`.`annotations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;

-- -----------------------------------------------------
-- Table `belexo`.`str_ann_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`str_ann_props` ;

CREATE TABLE IF NOT EXISTS `belexo`.`str_ann_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `value` TEXT NULL,
  `ann` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `sa_ann_idx` (`ann` ASC) VISIBLE,
  INDEX `sa_name_idx` (`name` ASC) VISIBLE,
  INDEX `sa_value_idx` (`value`(256) ASC) VISIBLE,
  INDEX `sa_name_ann_idx` (`name` ASC, `ann` ASC) VISIBLE,
  INDEX `sa_value_ann_idx` (`value`(256) ASC, `ann` ASC) VISIBLE,
  CONSTRAINT `sa_ann_fk`
    FOREIGN KEY (`ann`)
    REFERENCES `belexo`.`annotations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


-- -----------------------------------------------------
-- Table `belexo`.`int_ann_props`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `belexo`.`int_ann_props` ;

CREATE TABLE IF NOT EXISTS `belexo`.`int_ann_props` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NOT NULL,
  `value` INT NULL,
  `ann` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `ia_ann_idx` (`ann` ASC) VISIBLE,
  INDEX `ia_name_idx` (`name` ASC) VISIBLE,
  INDEX `ia_value_idx` (`value` ASC) VISIBLE,
  INDEX `ia_name_ann_idx` (`name` ASC, `ann` ASC) VISIBLE,
  INDEX `ia_value_ann_idx` (`value` ASC, `ann` ASC) VISIBLE,
  CONSTRAINT `ia_ann_fk`
    FOREIGN KEY (`ann`)
    REFERENCES `belexo`.`annotations` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = UTF8MB4
COLLATE = UTF8MB4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
